#!/bin/bash

echo "[INFO] Make sure that you execute the installer in /exfdb directory!"
echo "[#] Sleeping 6 seconds... Read the info!"
sleep 6

sudo rm /usr/bin/exfdb
sudo cp build-lib/exfdb /usr/bin/exfdb
chmod 777 /usr/bin/exfdb
sudo rm -d -rf /usr/share/exfdb
sudo cp ../exfdb /usr/share/exfdb -r
echo "[INFO] Reinstallation completed!";
